name: Package Application with Pyinstaller

on:
  push:
    tags:
      - '*'
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: ./src
    - name: Zip
      run: pushd . && cd ./src/dist/windows && zip -r ../../../windows.zip main && popd
    - uses: ncipollo/release-action@v1
      with:
        artifacts: windows.zip
