name: Package Application with Pyinstaller

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: ./
    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/windows
    - name: Zip
      run: zip -r windows.zip dist/windows
    - uses: ncipollo/release-action@v1
      with:
        artifacts: windows.zip
